import { FlatCompat } from '@eslint/eslintrc';
import js from '@eslint/js';
import typescript from '@typescript-eslint/eslint-plugin';
import typescriptParser from '@typescript-eslint/parser';
import nextPlugin from '@next/eslint-plugin-next';
import globals from 'globals';
import path from 'path';
import { createRequire } from 'module';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const require = createRequire(import.meta.url);
const noDirectConvexInOfflineCore = require('./eslint-rules/no-direct-convex-in-offline-core.cjs');

const compat = new FlatCompat({
  baseDirectory: __dirname,
  recommendedConfig: js.configs.recommended,
});

export default [
  // Ignore patterns (equivalent to .eslintignore)
  {
    ignores: [
      '.next/**',
      'node_modules/**',
      'out/**',
      'build/**',
      'dist/**',
      '.cache/**',
      'public/**',
      '*.config.js',
      '*.config.mjs',
      'next-env.d.ts', // Auto-generated by Next.js
    ],
  },

  // Base recommended configs
  js.configs.recommended,

  // TypeScript configuration
  {
    files: ['**/*.ts', '**/*.tsx', '**/*.js', '**/*.jsx'],
    languageOptions: {
      parser: typescriptParser,
      parserOptions: {
        ecmaVersion: 'latest',
        sourceType: 'module',
        ecmaFeatures: {
          jsx: true,
        },
      },
      globals: {
        ...globals.browser,
        ...globals.node,
        ...globals.es2021,
        React: 'readonly',
      },
    },
    plugins: {
      '@typescript-eslint': typescript,
      '@next/next': nextPlugin,
    },
    rules: {
      // TypeScript recommended rules
      ...typescript.configs.recommended.rules,
      
      // Next.js core rules
      ...nextPlugin.configs.recommended.rules,
      ...nextPlugin.configs['core-web-vitals'].rules,

      // Custom overrides (if needed)
      '@typescript-eslint/no-unused-vars': [
        'warn',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
        },
      ],
      '@typescript-eslint/no-explicit-any': 'warn',
      // User media and Convex URLs are dynamic; next/image remotePatterns cannot cover every host.
      '@next/next/no-img-element': 'off',
      // Material Symbols via Google Fonts stylesheet; next/font does not expose this family.
      '@next/next/no-page-custom-font': 'off',
    },
  },

  // TypeScript-specific overrides
  {
    files: ['**/*.ts', '**/*.tsx'],
    rules: {
      // TypeScript's compiler handles this better than ESLint
      'no-undef': 'off',
    },
  },

  // JavaScript-only files (less strict)
  {
    files: ['**/*.js', '**/*.jsx'],
    rules: {
      '@typescript-eslint/no-var-requires': 'off',
    },
  },

  // Local-first Offline Core guard (web port of mobile's KFM-114 rule). These surfaces must use
  // the offline bridge (@/lib/offline), not convex/react hooks, for local-first data.
  // Scope is expanded route-by-route as each surface is migrated onto the bridge; routes still on
  // the legacy cosplayNodes/buildTasks model (build-detail/[id], conventions/[id], builds) are
  // intentionally NOT listed yet — they are cleaned by the Phase 1/2 data-model migration.
  {
    files: [
      'src/app/elements/**/*.tsx',
      'src/app/planner/**/*.tsx',
      'src/app/packing/**/*.tsx',
      'src/app/itinerary/**/*.tsx',
      'src/app/settings/data/**/*.tsx',
    ],
    plugins: {
      kyarafit: { rules: { 'no-direct-convex-in-offline-core': noDirectConvexInOfflineCore } },
    },
    rules: {
      'kyarafit/no-direct-convex-in-offline-core': 'error',
    },
  },
];
